
modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] 
modId="geosmelt" #mandatory
version="1.7" #mandatory
displayName="GeoSmelt" #mandatory

logoFile="geosmelt.png" 
credits="The Forge team for making Forge."
authors="Witherlord00" 
description='''Who reads these?!'''

[[dependencies.geosmelt]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.geosmelt]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
